### ISSUE TITLE
Provide androidTest manifest to permit overriding of support libraries & fix minSdkVersion

### ISSUE THREAD

**Issue by BrantApps** [mauron85/background-geolocation-android#14]
This project pulls in `com.intentfilter:android-permissions:0.1.6` which has a `minSdkVersion` of 16. However, the minSdkVersion of [this project](https://github.com/mauron85/background-geolocation-android/blob/master/build.gradle#L39) is *15* causing this compilation error;
```
* What went wrong:
Execution failed for task ':react-native-mauron85-background-geolocation-common:processDebugAndroidTestManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 15 cannot be smaller than version 16 declared in library [com.intentfilter:android-permissions:0.1.6] /Users/davidb/.gradle/caches/transforms-1/files-1.1/android-permissions-0.1.6.aar/21d8aae82bf96cbf2bd50d472a4ce034/AndroidManifest.xml as the library might be using APIs not available in 15
        Suggestion: use a compatible library with a minSdk of at most 15,
                or increase this project's minSdk version to at least 16,
                or use tools:overrideLibrary="com.intentfilter.androidpermissions" to force usage (may lead to runtime failures)
```
Notice that this happens when compiling under the `androidTest` scope and specifically I've replicated when compiling the library under a React Native project. This problem doesn't appear to manifest in other compile scopes. I suspect `androidTest` is unique owing to the _Espresso_ and instrumentation resources that are pulled in. Whilst attempting to use [`wix/detox`](https://github.com/wix/detox) together with this library another issue was found;
```
* What went wrong:
Execution failed for task ':react-native-mauron85-background-geolocation-common:processDebugAndroidTestManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(26.0.1) from [com.android.support:appcompat-v7:26.0.1] AndroidManifest.xml:28:13-35
        is also present at [com.android.support:support-v4:26.1.0] AndroidManifest.xml:28:13-35 value=(26.1.0).
        Suggestion: add 'tools:replace="android:value"' to <meta-data> element at manifestMerger1108134589647091783.xml:26:9-28:38 to override.
```
This issue can be overcome by adding a meta-data block as described to the `androidTest` `AndroidManifest.xml`. I am able to submit both of these changes via a PR which I'll create shortly after this.

Would a contribution such as this be appropriate?

**Comment by mauron85** [comment]
Not sure if bumping minsdk bring something useful to the table. Specially, when you can fix your problem, by following that gradle suggestion and add 
`tools:replace="android:value"`

to your manifest.

**Comment by BrantApps** [comment]
That suggestion would need implementing on this library's androidTest `AndroidManifest`. Overriding from consumer manifests such as our app didn't work since compilation fails before our app manifest has time to be merged. I can do this if you like.

Regarding what bumping the `minSdkVersion` brings then it is correctness and runtime safety. If this `com.intentfilter:android-permission` library @0.1.6 uses an API introduced in API 16 then an app running on API 15 would runtime crash. This is alluded to in the compilation error;

```(may lead to runtime failures```

**Comment by leighman** [comment]
Hi. I'm also hitting this. Below sounds like a reasonable thing if you're depending on a dep that requires API 16. Cheers

> Regarding what bumping the `minSdkVersion` brings then it is correctness and runtime safety. If this `com.intentfilter:android-permission` library @0.1.6 uses an API introduced in API 16 then an app running on API 15 would runtime crash. This is alluded to in the compilation error;

**Comment by mauron85** [comment]
I think it's possible to make minSdkVersion configurable via ext prop.

EDIT: will merge such PR if somebody is willing to do it

**Comment by jwaldrip** [comment]
Running into this as well, @mauron85 how do I use tools:replace in my apps main manifest?

**Comment by mauron85** [comment]
Now minSdkVersion can be configurable via ext prop.

https://github.com/mauron85/react-native-background-geolocation#dependencies

**Comment by mauron85** [comment]
Thank you for raising this.
