### ISSUE TITLE
Rename account to something less obtuse

### ISSUE THREAD

**Issue by BrantApps** [mauron85/background-geolocation-android#18]
Hi again @mauron85,

Would you consider accepting a PR for renaming the `SyncService` account to something else? I understand the adapter is only a dummy but perhaps something less techy would sit better with users like "Location Synchronisation". I am referring to [this line](https://github.com/mauron85/background-geolocation-android/blob/08374b8f3f95b625c6e04e335fc38cc17338517e/src/main/java/com/marianhello/bgloc/BackgroundGeolocationFacade.java#L486) and [this](https://github.com/mauron85/background-geolocation-android/blob/07df724e01aaeb9dcaef63b95d4712ecbbd33a53/src/main/java/com/marianhello/bgloc/LocationService.java#L200).

This is how it looks to the user;

![screenshot_20181002-165557](https://user-images.githubusercontent.com/1109992/46361775-5c29b080-c666-11e8-8321-c80383056c6b.png)

Thank you for your time and let me know.

**Comment by mauron85** [comment]
Sorry, I missed somehow this. Yes, that's good idea.

**Comment by mauron85** [comment]
PR welcome

**Comment by BrantApps** [comment]
Great. Will rebase and submit this week

**Comment by mauron85** [comment]
FYI. Now you can configure account name in `android/app/src/main/res/values/strings.xml`

```
...
<string name="account_name">Sync Locations</string>
...
```
