### ISSUE TITLE
Missing JUnit dependency

### ISSUE THREAD

**Issue by danielgindi** [mauron85/background-geolocation-android#26]
Is it possible you are missing 
```
    [configuration: "implementation", dependency: testLibs.junit],
```

in `build.gradle`?

Because I suddenly cannot compile without it. The actual code (not tests) actually references `JUnit` for `Assert`, so it makes sense. It shouldn't have worked before :-)

**Comment by matthijsbierman** [comment]
Duplicate of https://github.com/mauron85/background-geolocation-android/issues/25?
