### ISSUE TITLE
Unable to use library with commons-io

### ISSUE THREAD

**Issue by petrleocompel** [mauron85/background-geolocation-android#29]
My project has dependency on `commons-io` wich conflicts with your placed classes in -> 
`src/main/java/org/apache/commons/io/`

You probably should use dependency `commons-io:commons-io:2.6`.
Add to `VERSIONS.gradle` after line 132
```
        commonsio: [group: 'commons-io', name:'commons-io', version: '2.6'],
```
To `build.gradle` in array `oreoDependencies`
```
    [configuration: "implementation", dependency: libs.commonsio],
```
And to array `preoreoDependencies`
```
    [configuration: "compile", dependency: libs.commonsio],
```

**Comment by tankers746** [comment]
Have made a PR for this: https://github.com/mauron85/background-geolocation-android/pull/31

**Comment by tankers746** [comment]
@mauron85 would it be possible to get this merged? Its interfering with expo's unimodules.

**Comment by petrleocompel** [comment]
Almost year  - still waiting...
Next problem is going to be release of older version of mauron85/react-native-background-geolocation
Using version 0.5

**Comment by himat** [comment]
@petrleocompel Just wanted to say thank you for posting this fix. I already spent so many hours trying to get the library to compile in release mode, and your PR finally helped me get it to work. Thank you for being here for this library since @mauron85 isn't even looking at it anymore.

**Comment by petrleocompel** [comment]
There is "maintained" fork which implemented this. -> https://github.com/darron1217/background-geolocation-android/ 
And in react-native part https://github.com/darron1217/react-native-background-geolocation 

I am closing this because it is 3 years later and no change.
