### ISSUE TITLE
Sync locations

### ISSUE THREAD

**Issue by luigidt** [mauron85/background-geolocation-android#32]
First, I'm not sure it's an issue or intended behavior.

I noticed that the "post" method of PostLocationTask will only try to sync the stored locations if:

- it has no connectivity (in this case we can assume that it will probably fail to sync)
- if the post fails (probably sync will fail too)
- if there is no "url" param in config

I'm not sure if there is something I don't see here. But it seems like this return statement shouldn't be there:

https://github.com/mauron85/background-geolocation-android/blob/3679c4273a9a7d0436fcd877a55d74e3c86e840a/src/main/java/com/marianhello/bgloc/PostLocationTask.java#L116

Thanks for any help :)

**Comment by mauron85** [comment]
That return statement is just fine. It basically prevents syncing location that was already successfuly posted.

**Comment by luigidt** [comment]
Isn't it preventing the sync of other stored locations?

I'm doing some tests, but it seems that if I don't comment this return it never tries to sync... perhaps I shouldn't provide an url if I want stored locations?

Thanks for your answer

**Comment by mauron85** [comment]
There are two concepts of sending locations to the server. First is posting location as soon as it is recorded by the device and second is location syncing of failed to post locations to the syncUrl in a single batch.

EDIT: If you don't provide `url` config option, then only (second) batch syncing will occur as soon location count reaches `syncThreshold`.
